src/routes/WidgetCreateRoute.js
Added refetch of widgetInstance after submitting, to ensure memoized version is never out of date
=> ERM-1611: Fixed cached resource showing up on first edit

src/components/Widget/Widget.js
* set scope property of HasCommand to Widget.children
=> ERM-1756 add edit widget FOLIO keyboard shortcut

src/components/TypeComponents/SimpleSearch/Form/filters/SimpleSearchDateFilterField.js, src/components/TypeComponents/SimpleSearch/Form/filters/SimpleSearchFilterArray.js, src/components/TypeComponents/SimpleSearch/Form/filters/SimpleSearchFilterFields.css, src/components/TypeComponents/SimpleSearch/Form/filters/SimpleSearchFilterRuleArray.js, src/components/TypeComponents/SimpleSearch/Form/filters/SimpleSearchUUIDFilterField.js, src/components/TypeComponents/SimpleSearch/Form/filters/filters.css, translations/ui-dashboard/en.json
Formatting and styling changes to OR and AND between filters/rules
=> ERM-1689: Dashboard: Simple search widget filters: display of AND / OR conditions

src/components/WidgetForm/WidgetForm.js, src/routes/WidgetCreateRoute.js, translations/ui-dashboard/en.json
added 'x' and appicon to create/edit screens
refs - ERM-1699: Dashboard: Update the Edit widget pane header
=> ERM-1698: Dashboard: Add a close icon and app icon to the New widget pane header

src/components/TypeComponents/SimpleSearch/Form/filters/SimpleSearchDateFilterField.js, src/components/TypeComponents/SimpleSearch/Form/filters/SimpleSearchFilterField.js, src/components/TypeComponents/SimpleSearch/Form/filters/SimpleSearchFilterRuleField.js, src/components/TypeComponents/SimpleSearch/Form/filters/SimpleSearchUUIDFilterField.js
=> A11y improvements

CHANGELOG.md, package.json, src/components/ReorderForm/ReorderForm.js, translations/ui-dashboard/en.json, translations/ui-dashboard/en_US.json
* add appIcon, dismissible and onClose properties to Pane in ReorderForm component, refs ERM-1792
* change translation key value for reorderForm.paneTitle in en.json and en_US.json, refs ERM-1792
* change translation key value for editWidget in en.json and en_US.json, refs ERM-1855
=> UX improvements for Dashboard

CHANGELOG.md, package.json
Updated dependencies and changelog
ERM-2026
=> chore: Release 2.2.0

CHANGELOG.md, package.json, src/index.js, src/routes/DashboardOrderRoute.js, src/routes/DashboardRoute.js, src/routes/DashboardsRoute.js, src/routes/WidgetCreateRoute.js, src/routes/WidgetEditRoute.js
Reverts folio-org/ui-dashboard#175
*sigh* revert ping pong here we go
=> Revert "Revert "ERM-2312: Managed Dashboards: backend model (refactor to avoid regressions)""

package.json
* add stripes-erm-components as peer and dev dependency
* remove it from 'dependencies'
=> ERM-2319 stripes-erm-components should be a peer

__mocks__/@folio/stripes-erm-components.js, __mocks__/@folio/stripes/components.js, __mocks__/@folio/stripes/core.js, __mocks__/@folio/stripes/smart-components.js, __mocks__/@k-int/stripes-kint-components.js, __mocks__/currency-codes/data.js, __mocks__/react-query.js, __mocks__/react-router-dom.js, __mocks__/stripes-config.js, jest.config.js, package.json, src/components/ActionMenu/ActionMenu.test.js, src/components/Dashboard/NoWidgets/NoWidgets.test.js, src/components/DashboardContainer/Header/Header.test.js, src/components/Loading/Loading.test.js, src/components/TypeComponents/SimpleSearch/Widget/simpleSearchPathBuilder.test.js, src/components/UserAccessFieldArray/UserAccessFieldArray.test.js, src/components/Widget/Widget.test.js, src/components/Widget/WidgetFooter.test.js, src/components/Widget/WidgetHeader.test.js, src/tokens.test.js, test/helpers/translationsProperties.js
Moved all jest tests over to manual mocks and imports from stripes-erm-testing
=> test: erm-testing

src/components/hooks/useDashboardAccess.js, src/components/hooks/useDashboardAccessStore.js
=> ERM-2575 fix deprecated default export from 'zustand'

CHANGELOG.md, package.json
Updated CHANGELOG, ensured dependencies are up to date
ERM-2501
=> chore: Release 4.0.0

src/components/TypeComponents/SimpleSearch/Widget/SimpleSearch.js
used noopener norefferer to protect the URL against the Cross Sitte Scripting
=> SI-12, Potential CROSS SITE SCRIPTING (XSS) vulnerability

package.json, src/components/TypeComponents/SimpleSearch/Form/configurableProperties/SimpleSearchConfigurableProperties.js, src/components/TypeComponents/utilities/validators.js
fix: URI Validation
Outsourced the "is this a valid URL" question to javascript/validator library, so that responsibility for upkeeping security is not on our shoulders.
SI-23
=> SI-23: URL validation in simple search widget is too strict

src/components/TypeComponents/SimpleSearch/Form/SimpleSearchForm.js, src/components/TypeComponents/SimpleSearch/Widget/SimpleSearch.js
Solved two small issues in dashboard code
=> chore: Problems

package.json
Added okapi interface dependency on new servint interface 3.0
refs ERM-2641
=> build: servint 3.0

src/components/TypeComponents/SimpleSearch/Form/configurableProperties/SimpleSearchConfigurableProperties.js, src/components/TypeComponents/utilities/index.js, src/components/TypeComponents/utilities/validators.js, translations/ui-dashboard/en.json
* add validator for input size of url field
=> SI-25 In UI limit  length of widget URL input to 2048 chars

src/routes/DashboardsRoute.js
* use `useParallelBatchFetch` hook instead of `useQuery` for dashboard users
=> ERM-3014 Manage user access allows display of 10 users max

src/components/UserAccessFieldArray/UserAccessFieldArray.js, src/routes/DashboardAccessRoute.js
=> ERM-3040 Dashboard: "New" badge is wrapping onto two lines

CHANGELOG.md, package.json
Updated CHANGELOG and dependencies for 5.0.0 release
[ERM-2659](https://issues.folio.org/browse/ERM-2659)
=> chore: Release 5.0.0

src/components/DashboardContainer/Header/Header.js, src/components/WidgetForm/WidgetForm.js
Do not display error when no widgetDefinition has yet been selected. Also small tweak to Header styling
=> fix: Minor tweak to error handling in form

src/components/TypeComponents/SimpleSearch/Form/results/SimpleSearchResultField.js, src/components/WidgetForm/WidgetForm.js
* remove if statement
* add comment
=> ERM-3122 On editing a widget, the top of the widget configuration screen should display

CHANGELOG.md
=> ERM-3106 ui-dashboard release

src/routes/DashboardsRoute.js
* add perPage param to DashboardsRoute
=> SI-55 Dashboard app displays only the first 10 dashboards

package.json
Tinmy change, only here to force github actions to fire so I can change settings -.- This is a terrible system
=> build: Bump kint-comps minimum

src/routes/DashboardsRoute.js
Last PR changed order of some imports due to auto save behaviour in VScode, testing turning that off again
=> style: Nothingburger import order change

GUIDANCE.md, LICENSE
Updated license and added guidance.md file
=> ERM-3376: Update module license and guidance

CHANGELOG.md, package.json
Bumped version to 7.1.0, added new CHANGELOG.md section
=> chore: Post release 7.0.0
